server:
  port: 9050
  servlet:
    context-path: /
spring:
  application:   #定义服务名称
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4999/eureka
  instance:
    instance-id: springcloud-zuul-9050             #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
zuul:
  #prefix: /                             #通过统一的公共前缀
